language: cpp
matrix:
  include:
  - os: linux
    env:
    - TARGET_ARCHITECTURE=x86_64
    - TRAVIS_NODE_VERSION="6"
    compiler:
    - gcc
    install:
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd
      ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh
      && nvm install $TRAVIS_NODE_VERSION
    addons:
      apt:
        packages:
        - cmake
        - libsqlite3-dev
        - curl
        - libcurl4-openssl-dev
        - libssl-dev
        - libavahi-client-dev
    script:
    - cmake -DDEBUG=OFF . && make && cd www && npm install && npm run build_prod &&
      cd ..
  - os: osx
    env:
    - TARGET_ARCHITECTURE=x86_64
    - TRAVIS_NODE_VERSION="6"
    compiler:
    - gcc
    install:
    - brew update
    - brew install libusb
    - brew install libusb-compat
    - brew install openssl
    - export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd
      ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh
      && nvm install $TRAVIS_NODE_VERSION
    script:
    - cmake -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DOPENSSL_INCLUDE_DIRS=/usr/local/opt/openssl/include/
      -DDEBUG=OFF . && make && cd www && npm install && npm run build_prod && cd ..
before_deploy:
- tar -C .. -czf micasa_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz micasa/micasa
  micasa/lib/open-zwave/config micasa/www/index.html micasa/www/index.appcache micasa/www/css
  micasa/www/fonts micasa/www/tpl micasa/www/app/app.min.js
- shasum -a 256 micasa_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz > micasa_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz.sha256sum
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "j4ltkq84UPUkx30zc/pMts31PShj+ondHB+rakICxxt5i+7Q3YoYk1oseVoIyxjfnsug0+DhPloefDncEJWBQRv10Wzhb/ZxUTPz0MWTYsjHq9z5QDmLdFlNNvjJTHGyTd0b+CaXvuPELslIayjFfPLa9VZstvkocdZb45ZPT9B0l1XlQJ4aUvLdQjWWYAEb81AIukukyYRKqjGGxGaekIY66NPRNRCZRd9lRRAHDoygsHMPD5Omta4Y3AS/Nins/JE8klM6ihvmBZzQ/4CBxKsG0AiB+YjE15g1meJiLBk9Sgbd8vXEV/udpImcHKtJxnHoJqcNaVC2GtzowG7wKyftwpJGlpO61/o5JskfZFFRv6pPglVdx62IIBoCbBv9lD6RPOoUzOMjMk9BbATsHH5AFBHUBPc9pB39uqwJHPyt9ODdXDXZ1nLLhigsQVoN7ucYIhn7poqTe9uczOC0ohgdlE2c+jaJue+nMn/p7SghdthP2xq7rh0tKPawfSSemECz8/2ouYSwsm5isa3Lvxw6RAmuy+++BorJhDO2I1cr51T0QEqOFUtL2UIjgC3yFjnH+ph7CxXfTvMblRDEl5jrWrjXk/hc8qNdIDO8PXzHswWnjrvA97KrKwAfT6lH2zQU33zxnzPNIPaQhKUN6RvOYxgkW6HCmYlezGGL/Dg=" 
  file:
  - micasa_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz
  - micasa_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz.sha256sum
  on:
    repo: fellownet/micasa
    tags: true
